### ISSUE TITLE
EasyMotion: other editor

### ISSUE THREAD

**Issue by Alexey-T** [rogercloud/SubEasymotion#1]
Hi. Good work on ST code. Do you think it's possible to make this for Synwrite?
https://sourceforge.net/p/synwrite/wiki/python%20API/

for donation from me

**Comment by rogercloud** [comment]
EasyMotion is a plugin for vi mode, but I find no vim plugin for synwrite. Maybe a vi plugin is the first step?

**Comment by Alexey-T** [comment]
Hi. vi mode is 1st step?? no no. Just can write EasyMot py code, no vim mode needed.

Synw has all API already (for EasyMot)
